spring:
  datasource:
    url: jdbc:h2:mem:test
    username: guardjo
    password: 1234
    driver-class-name: org.h2.Driver
  sql:
    init:
      mode: always

  h2:
    console:
      enabled: true
