spring:
  datasource:
    url: jdbc:h2:mem:simple
    username: manager
    password: manager0
    driver-class-name: org.h2.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true